Lint/EndAlignment:
  AutoCorrect: true
Style/SymbolArray:
  MinSize: 3
  
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false